# 101 NumPy Exercises for Data Analysis

## Source: [Machine Learning Plus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

### 001 - L1: Import numpy as np and print the version number. 

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.1


### 002 - L1: Create a 1D array of numbers from 0 to 9

In [26]:
np.arange(10) # Could be np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 003 - L1: Create a 3×3 numpy array of all True’s

In [8]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 004 - L1: Extract all odd numbers from arr

In [21]:
arr = np.arange(10)

In [17]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

### 005 - L1: Replace all odd numbers in arr with -1

In [22]:
arr = np.arange(10)

In [19]:
arr[arr%2!=0] = -1

In [20]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 006 - L2: Replace all odd numbers in arr with -1 without changing arr

In [3]:
arr = np.arange(10)

In [14]:
out = np.where(arr%2!=0, -1, arr)

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 007 - L1: Convert a 1D array to a 2D array with 2 rows

In [23]:
arr = np.arange(10)  

In [25]:
arr.reshape(2,5) # Could be arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 008 - L2: Stack arrays a and b vertically

In [29]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [41]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
arr = np.append(a, b, axis=0) # Alternatives: concatenate, vstack

In [36]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 009 - L2: Stack the arrays a and b horizontally

In [38]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [39]:
arr = np.append(a, b, axis=1) # Alternatives: concatenate, hstack

In [40]:
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 010 - L2: Create the following pattern without hardcoding.
#### Note: Use only numpy functions and the below input array a
#### array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [46]:
a = np.array([1,2,3])

In [70]:
b = np.concatenate([a, a, a], axis=0)

In [78]:
c = np.append(a, b)

In [72]:
b

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [79]:
c

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 011 - L2: Get the common items between a and b

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [44]:
arr = np.intersect1d(a, b)

In [45]:
arr

array([2, 4])

### 012 - L2: From array a remove all items present in array b 