# 101 NumPy Exercises for Data Analysis

### Source: [Selva Prabhakaran on Machine Learning Plus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

### 001 - L1: Import Numpy and print the version number. 

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.18.1


### 002 - L1: Create a 1D array of numbers from 0 to 9

In [4]:
np.arange(10) # Could be np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 003 - L1: Create a 3×3 numpy array of all True’s

In [5]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 004 - L1: Extract all odd numbers from arr

In [6]:
arr = np.arange(10)

In [7]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

### 005 - L1: Replace all odd numbers in arr with -1

In [8]:
arr = np.arange(10)

In [9]:
arr[arr%2!=0] = -1

In [10]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 006 - L2: Replace all odd numbers in arr with -1 without changing arr

In [11]:
arr = np.arange(10)

In [12]:
out = np.where(arr%2!=0, -1, arr)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 007 - L1: Convert a 1D array to a 2D array with 2 rows

In [15]:
arr = np.arange(10)  

In [16]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 008 - L2: Stack arrays a and b vertically

In [17]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

In [18]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
arr = np.append(a, b, axis=0) # Alternatives: concatenate, vstack

In [21]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 009 - L2: Stack the arrays a and b horizontally

In [22]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

In [23]:
arr = np.append(a, b, axis=1) # Alternatives: concatenate, hstack

In [24]:
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 010 - L2: Create the following pattern without hardcoding.
#### Note: Use only numpy functions and the below input array a
#### array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [25]:
a = np.append(np.array([1,2,3]).repeat(3),np.tile(np.array([1,2,3]),3))
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 011 - L2: Get the common items between a and b

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [27]:
arr = np.intersect1d(a, b)
arr

array([2, 4])

### 012 - L2: From array a remove all items present in array b 

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [29]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 013 - L2: Get the positions where elements of a and b match

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [36]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 014 - Get all items between 5 and 10 from a

In [32]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [33]:
a[(a >= 5) & (a<=10)]

array([ 6,  9, 10])