#### L1: Import numpy as np and print the version number. 

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.18.1


#### L1: Create a 1D array of numbers from 0 to 9

In [15]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### L1: Create a 3×3 numpy array of all True’s

In [8]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### L1: Extract all odd numbers from arr

In [16]:
arr = np.array(range(0,10))

In [17]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

#### L1: Replace all odd numbers in arr with -1

In [18]:
arr = np.array(range(0,10))

In [19]:
arr[arr%2!=0] = -1

In [20]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])